### ISSUE TITLE
getAnnotationParams() failing

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#50]
Fails for:

13: Arabidopsis thaliana genes (TAIR10 (2010-09-TAIR10))
13: UniProtKB/SwissProt ID(s)

66: Drosophila melanogaster genes (BDGP5)
17: UniProt/Swissprot Accession(s) [e.g. P08111]

95: Homo sapiens genes (GRCh38)
15: UniProt/Swissprot Accession(s) [e.g. Q13068]
but this works
16: UniProt/Swissprot ID(s) [e.g. Q9H3N8]

120: Mus musculus genes (GRCm38.p3)
15: UniProt/Swissprot Accession(s) [e.g. Q8K2Q7]
but this works
16: UniProt/Swissprot ID(s) [e.g. P03888]

**Comment by lmsimp** [comment]
Selecting 16 UniProt/Swissprot Accession(s) for human and mouse work fine when R is called from command line but not in RStudio?

**Comment by lgatto** [comment]
@lmsimp please install again from github (still verion 1.9.1). It should work now.

**Comment by lmsimp** [comment]
Thank you very much for sorting this.

**Comment by lgatto** [comment]
Could you regenerate the human an mouse numbers. We'll also have to document the biomart and ensembl versions used. 


On 24 April 2015 07:01:03 BST, Lisa Breckels <notifications@github.com> wrote:
>Thank you very much for sorting this.
>
>> On 24 Apr 2015, at 03:29, Laurent Gatto <notifications@github.com>
>wrote:
>> 
>> @lmsimp please install again from github (still verion 1.9.1). It
>should work now.
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/lgatto/pRoloc/issues/50#issuecomment-95810640

-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by lmsimp** [comment]
Yes will do. Strangely, still having issues in RStudio but from command line is fine.

**Comment by lgatto** [comment]
For the record, new marts are:

```
##           biomart                      version
## 1         ensembl ENSEMBL GENES 79 (SANGER UK)
## 5   fungi_mart_26    ENSEMBL FUNGI 26 (EBI UK)
## 7 metazoa_mart_26  ENSEMBL METAZOA 26 (EBI UK)
## 9  plants_mart_26   ENSEMBL PLANTS 26 (EBI UK)
```

old ones were `biomart` (previous ENSEMBL GENES ??), `fungi_mart_25`, `metazoa_mart_25` and `plants_mart_25`.
